name: temp-cifar-download
on:
  push:
    paths:
      - '.github/workflows/temp-cifar-download.yml'
jobs:
  download:
    runs-on: ubuntu-24.04
    steps:
      - name: Download CIFAR-10
        run: |
          curl -L --fail --retry 3 https://dataset.bj.bcebos.com/cifar/cifar-10-python.tar.gz -o cifar-10-python.tar.gz
          sha256sum cifar-10-python.tar.gz
      - name: Upload CIFAR-10
        uses: actions/upload-artifact@v4
        with:
          name: cifar10-data
          path: cifar-10-python.tar.gz
          retention-days: 1
